# Generated by Django 4.0.10 on 2024-02-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessUnit',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('businessUnitName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='costCenter',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('costCenterName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='deparment',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('deparmentName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('codeValue', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=255)),
                ('locationName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('associateOID', models.CharField(max_length=55)),
                ('WorkerId', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('workerStatus', models.CharField(choices=[('Active', 'Active'), ('Terminated', 'Terminated'), ('Leave', 'Leave')], max_length=10)),
                ('prefered_name', models.CharField(max_length=55)),
                ('prefered_lastName', models.CharField(max_length=55)),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('businessUnitCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businessunit')),
                ('companyCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('costCenterCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.costcenter')),
                ('departmentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deparment')),
                ('jobTitleCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('locationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
    ]
