# Generated by Django 4.0.10 on 2024-02-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessunit_company_costcenter_deparment_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='businessUnitCode',
            new_name='businessUnit',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='companyCode',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='costCenterCode',
            new_name='costCenter',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='departmentCode',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='jobTitleCode',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='locationCode',
            new_name='location',
        ),
    ]
