# Generated by Django 4.0.10 on 2024-02-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_workers_businessunit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessunit',
            old_name='businessUnitName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='companyName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='costcenter',
            old_name='costCenterName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='deparment',
            old_name='deparmentName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobTitle',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locationName',
            new_name='name',
        ),
    ]
