# Generated by Django 4.0.10 on 2024-02-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_location_businessunits_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='businessUnits',
        ),
        migrations.DeleteModel(
            name='costCenters',
        ),
        migrations.DeleteModel(
            name='jobs',
        ),
        migrations.DeleteModel(
            name='locations',
        ),
        migrations.AlterField(
            model_name='workers',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
        migrations.DeleteModel(
            name='deparments',
        ),
    ]
