# Generated by Django 4.0.10 on 2024-02-14 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_businessunits_delete_costcenters_delete_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
    ]
