# Generated by Django 4.0.10 on 2024-02-16 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workers_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
