# Generated by Django 4.0.10 on 2024-02-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companies',
            new_name='CommonCodeListFields',
        ),
        migrations.CreateModel(
            name='companies',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
    ]
