# Generated by Django 4.0.10 on 2024-02-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_companies_commoncodelistfields_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='businessUnits',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
        migrations.CreateModel(
            name='costCenters',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
        migrations.AlterField(
            model_name='workers',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companies'),
        ),
    ]
