# Generated by Django 4.0.10 on 2024-02-16 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_businessunits_costcenters_departments_jobs_locations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobs',
        ),
        migrations.CreateModel(
            name='title',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.commoncodelistfields',),
        ),
    ]
