# Generated by Django 4.0.10 on 2024-02-16 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_businessunits_delete_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='businessUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.businessunits'),
        ),
    ]
