# Generated by Django 4.0.10 on 2024-02-16 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_workers_businessunit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='title',
            new_name='titles',
        ),
        migrations.AddField(
            model_name='workers',
            name='costCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.costcenters'),
        ),
        migrations.AddField(
            model_name='workers',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departments'),
        ),
        migrations.AddField(
            model_name='workers',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.locations'),
        ),
        migrations.AddField(
            model_name='workers',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.titles'),
        ),
    ]
