# Generated by Django 4.0.10 on 2024-02-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_title_titles_workers_costcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='TermDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='startDate',
            field=models.DateTimeField(null=True),
        ),
    ]
