# Generated by Django 4.0.10 on 2024-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workers_termdate_workers_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='TermDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
