# Generated by Django 4.0.10 on 2024-02-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_workers_termdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='businessUnits',
            new_name='businessUnit',
        ),
        migrations.RenameModel(
            old_name='companies',
            new_name='company',
        ),
        migrations.RenameModel(
            old_name='costCenters',
            new_name='costCenter',
        ),
        migrations.RenameModel(
            old_name='departments',
            new_name='department',
        ),
        migrations.RenameModel(
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameModel(
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
