# Generated by Django 4.0.10 on 2024-02-21 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_businessunits_businessunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lifeCycleEvent',
            fields=[
                ('life_event_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Complete', 'Complete')], max_length=10)),
                ('event_type', models.CharField(choices=[('Onboard', 'Onboard'), ('Offboard', 'Offboard'), ('Promotion', 'Promotion'), ('Transfer', 'Transfer')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('migration_window', models.IntegerField()),
                ('end_date', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='lifeCycleCase',
            fields=[
                ('life_cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Onboarding', 'Onboarding'), ('Hired', 'Hired'), ('Moving', 'Moving'), ('Leaving', 'Leaving'), ('Rehiring', 'Rehiring'), ('Archived', 'Archived')], max_length=15)),
                ('Event', models.ManyToManyField(blank=True, to='core.lifecycleevent')),
                ('Worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
        ),
    ]
