# Generated by Django 4.0.10 on 2024-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lifecycleevent_lifecyclecase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecyclecase',
            name='life_cycle_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lifecycleevent',
            name='life_event_id',
            field=models.CharField(editable=False, max_length=11, primary_key=True, serialize=False),
        ),
    ]
