# Generated by Django 4.0.10 on 2024-02-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lifecyclecase_life_cycle_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifecyclecase',
            old_name='status',
            new_name='case_status',
        ),
        migrations.RenameField(
            model_name='lifecycleevent',
            old_name='status',
            new_name='event_status',
        ),
    ]
