# Generated by Django 4.0.10 on 2024-02-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_status_lifecyclecase_case_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifecyclecase',
            name='Event',
        ),
        migrations.AddField(
            model_name='lifecycleevent',
            name='case_id',
            field=models.ForeignKey(default='LIFE-00001', on_delete=django.db.models.deletion.CASCADE, to='core.lifecyclecase'),
            preserve_default=False,
        ),
    ]
