# Generated by Django 4.0.10 on 2024-02-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_lifecyclecase_event_lifecycleevent_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecyclecase',
            name='Worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.worker'),
        ),
    ]
